const { GoogleSpreadsheet } = require('google-spreadsheet');
const creds = require('../../.jh_credentials.json');

const SHEET_ID = '1t3x3e7z71e5fquiF9sfKrXqeFwbQpF24Z4HeKWz9GY0';

/* https://console.developers.google.com/apis/credentials */
// const CLIENT_ID = '517958998706-q7obmo3b8can89f72ke29n3sfeljv4nf.apps.googleusercontent.com';
// const API_KEY = 'AIzaSyAukzKN9E3dpyfSZfuA2JZ5UkUfJH3VM3s';
// const SCOPE = 'https://www.googleapis.com/auth/spreadsheets';

const handleNewsletterFormSubmit = async (event) => {
  event.preventDefault();
  console.log('submitted!');
};

const init = async () => {
  const doc = new GoogleSpreadsheet(SHEET_ID);
  await doc.useServiceAccountAuth(creds);

  // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
  await doc.useServiceAccountAuth({
    // env var values are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    private_key: process.env.GOOGLE_PRIVATE_KEY,
  });

  await doc.loadInfo(); // loads document properties and worksheets
  console.log(doc.title);
  await doc.updateProperties({ title: 'renamed doc' });

  const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
  console.log(sheet.title);
  console.log(sheet.rowCount);

  document.getElementById('newsletter-signup').addEventListener('submit', handleNewsletterFormSubmit);
};

document.addEventListener('DOMContentLoaded', init);
